import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Navbar } from './Components/Navbar/navbar'
import FooterBar from "@/app/Components/FooterBar/FooterBar";
import {StoreProvider} from "@/app/Services/StateStore/StoreProvider";
import React from "react";
import 'bootstrap/dist/css/bootstrap.min.css';
import {SSRProvider} from "react-bootstrap";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <StoreProvider>

        <html lang="en">
          <body className={inter.className}>

            <Navbar></Navbar>
            {children}
            <FooterBar></FooterBar>
          </body>
        </html>

    </StoreProvider>
  )
}
